name: unit tests

on: [push, workflow_dispatch]

jobs:
  ruff:
    name: ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        name: ruff check
        with:
          args: 'check --output-format=github'
      - uses: chartboost/ruff-action@v1
        name: ruff format
        with:
          args: 'format --check'

  tests:
    name: python ${{ matrix.python-version }} on ${{ matrix.os }}
    needs: ruff
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: true
      - name: install dependencies
        run: pdm install -dG test -dG typing
      - name: mypy
        run: pdm run mypy
      - name: pytest
        run: pdm run pytest
      - name: coveralls.io
        uses: coverallsapp/github-action@v2
        with:
          flag-name: ${{ matrix.python-version }}, ${{ matrix.os }}
          parallel: true
          file: coverage.xml

  finish:
    needs: tests
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
